# Generated by Django 2.1.7 on 2019-04-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(default='unknown-validator', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='normalsentence',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_sentences', related_query_name='normal_sentence', to='mohaverekhan.Validator'),
        ),
        migrations.AddField(
            model_name='normaltext',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_texts', related_query_name='normal_text', to='mohaverekhan.Validator'),
        ),
        migrations.AddField(
            model_name='normalword',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_words', related_query_name='normal_word', to='mohaverekhan.Validator'),
        ),
        migrations.AddField(
            model_name='taggedsentence',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_sentences', related_query_name='tagged_sentence', to='mohaverekhan.Validator'),
        ),
    ]
