# Generated by Django 2.1.7 on 2019-04-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NLTKTagger',
        ),
        migrations.CreateModel(
            name='BitianistTokenizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tagger',),
        ),
        migrations.CreateModel(
            name='FormalTagger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tagger',),
        ),
        migrations.CreateModel(
            name='InformalTagger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tagger',),
        ),
        migrations.CreateModel(
            name='Seq2SeqNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
    ]
