# Generated by Django 2.1.7 on 2019-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokentag',
            name='number_of_repetitions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
