# Generated by Django 2.1.7 on 2019-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0002_auto_20190401_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizer',
            name='name',
            field=models.SlugField(allow_unicode=True, default='unknown-normalizer', unique=True),
        ),
        migrations.AlterField(
            model_name='tagger',
            name='name',
            field=models.SlugField(allow_unicode=True, default='unknown-tagger', unique=True),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='name',
            field=models.SlugField(allow_unicode=True, default='unknown-tag-set', unique=True),
        ),
        migrations.AlterField(
            model_name='validator',
            name='name',
            field=models.SlugField(allow_unicode=True, default='unknown-validator', unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
