# Generated by Django 2.1.7 on 2019-04-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0002_auto_20190405_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitianistTokenizer',
        ),
        migrations.DeleteModel(
            name='FormalTagger',
        ),
        migrations.DeleteModel(
            name='InformalTagger',
        ),
        migrations.DeleteModel(
            name='RefinementNormalizer',
        ),
        migrations.DeleteModel(
            name='ReplacementNormalizer',
        ),
        migrations.DeleteModel(
            name='Seq2SeqNormalizer',
        ),
        migrations.CreateModel(
            name='BitianistFormalNLTKTagger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tagger',),
        ),
        migrations.CreateModel(
            name='BitianistInformalNLTKTagger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tagger',),
        ),
        migrations.CreateModel(
            name='BitianistInformalRefinementNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
        migrations.CreateModel(
            name='BitianistInformalReplacementNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
        migrations.CreateModel(
            name='BitianistInformalSeq2SeqNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
        migrations.CreateModel(
            name='BitianistInformalTokenizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tokenizer',),
        ),
    ]
