# Generated by Django 2.1.7 on 2019-04-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0003_auto_20190405_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizer',
            name='show_name',
            field=models.CharField(default='اعتبارسنج نامشخص', max_length=200),
        ),
        migrations.AddField(
            model_name='tagger',
            name='show_name',
            field=models.CharField(default='اعتبارسنج نامشخص', max_length=200),
        ),
        migrations.AddField(
            model_name='tokenizer',
            name='show_name',
            field=models.CharField(default='اعتبارسنج نامشخص', max_length=200),
        ),
        migrations.AddField(
            model_name='validator',
            name='show_name',
            field=models.CharField(default='اعتبارسنج نامشخص', max_length=200),
        ),
    ]
