# Generated by Django 2.1.7 on 2019-04-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0003_remove_tag_examples'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normalizer',
            options={'ordering': ('created',), 'verbose_name': 'Normalizer', 'verbose_name_plural': 'Normalizers'},
        ),
        migrations.AlterModelOptions(
            name='tagger',
            options={'ordering': ('created',), 'verbose_name': 'Tagger', 'verbose_name_plural': 'Taggers'},
        ),
    ]
