# Generated by Django 2.1.7 on 2019-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0003_auto_20190401_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizer',
            name='name',
            field=models.SlugField(default='unknown-normalizer', unique=True),
        ),
        migrations.AlterField(
            model_name='tagger',
            name='name',
            field=models.SlugField(default='unknown-tagger', unique=True),
        ),
        migrations.AlterField(
            model_name='tagset',
            name='name',
            field=models.SlugField(default='unknown-tag-set', unique=True),
        ),
        migrations.AlterField(
            model_name='validator',
            name='name',
            field=models.SlugField(default='unknown-validator', unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
