# Generated by Django 2.1.7 on 2019-04-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0004_auto_20190406_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizer',
            name='show_name',
            field=models.CharField(default='نرمال\u200cکننده نامشخص', max_length=200),
        ),
        migrations.AlterField(
            model_name='tagger',
            name='show_name',
            field=models.CharField(default='برچسب\u200cزن نامشخص', max_length=200),
        ),
        migrations.AlterField(
            model_name='texttag',
            name='tagger',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_tags', related_query_name='text_tag', to='mohaverekhan.Tagger'),
        ),
        migrations.AlterField(
            model_name='tokenizer',
            name='show_name',
            field=models.CharField(default='قطعه\u200cکننده نامشخص', max_length=200),
        ),
    ]
