# Generated by Django 2.1.7 on 2019-04-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0004_auto_20190410_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitianistFormalNLTKTagger',
        ),
    ]
