# Generated by Django 2.1.7 on 2019-04-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0004_auto_20190401_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validator',
            options={'ordering': ('-created',), 'verbose_name': 'Validator', 'verbose_name_plural': 'Validators'},
        ),
    ]
