# Generated by Django 2.1.7 on 2019-04-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0005_auto_20190406_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttag',
            name='tagger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_tags', related_query_name='text_tag', to='mohaverekhan.Tagger'),
        ),
    ]
