# Generated by Django 2.1.7 on 2019-04-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0005_delete_bitianistformalnltktagger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitianistInformalNLTKTagger',
        ),
        migrations.DeleteModel(
            name='BitianistInformalRefinementNormalizer',
        ),
        migrations.DeleteModel(
            name='BitianistInformalReplacementNormalizer',
        ),
        migrations.DeleteModel(
            name='BitianistInformalSeq2SeqNormalizer',
        ),
        migrations.CreateModel(
            name='BitianistBasicNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
        migrations.CreateModel(
            name='BitianistRefinementNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
        migrations.CreateModel(
            name='BitianistRefinementTagger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tagger',),
        ),
        migrations.CreateModel(
            name='BitianistReplacementNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
        migrations.CreateModel(
            name='BitianistSeq2SeqNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
        migrations.CreateModel(
            name='BitianistSeq2SeqTagger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tagger',),
        ),
    ]
