# Generated by Django 2.1.7 on 2019-04-01 17:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0005_auto_20190401_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='is_normal',
        ),
        migrations.RemoveField(
            model_name='text',
            name='is_normal',
        ),
        migrations.RemoveField(
            model_name='word',
            name='is_normal',
        ),
        migrations.AddField(
            model_name='sentence',
            name='previous_normalizers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='text',
            name='previous_normalizers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='word',
            name='previous_normalizers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
