# Generated by Django 2.1.7 on 2019-04-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0006_auto_20190401_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
