# Generated by Django 2.1.7 on 2019-04-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0006_auto_20190413_0112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitianistRefinementNormalizer',
        ),
        migrations.DeleteModel(
            name='BitianistRefinementTagger',
        ),
        migrations.CreateModel(
            name='BitianistCorrectionNormalizer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.normalizer',),
        ),
        migrations.CreateModel(
            name='BitianistCorrectionTagger',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mohaverekhan.tagger',),
        ),
    ]
