# Generated by Django 2.1.7 on 2019-04-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0007_auto_20190401_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='previous_normalizers',
            new_name='normalizers_sequence',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='previous_normalizers',
            new_name='normalizers_sequence',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='previous_normalizers',
            new_name='normalizers_sequence',
        ),
    ]
