# Generated by Django 2.1.7 on 2019-04-07 06:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0007_auto_20190406_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='examples',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
