# Generated by Django 2.1.7 on 2019-04-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0008_tag_examples'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitianistInformalTokenizer',
        ),
        migrations.RenameField(
            model_name='texttag',
            old_name='tokens',
            new_name='tagged_tokens',
        ),
        migrations.RemoveField(
            model_name='texttag',
            name='tokenizer',
        ),
        migrations.DeleteModel(
            name='Tokenizer',
        ),
    ]
