# Generated by Django 2.1.7 on 2019-04-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mohaverekhan', '0009_auto_20190409_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_tags', related_query_name='token_tag', to='mohaverekhan.Tag')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_tags', related_query_name='token_tag', to='mohaverekhan.Token')),
            ],
        ),
        migrations.AddField(
            model_name='texttag',
            name='tagged_tokens_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='texttag',
            name='tags_string',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='texttag',
            name='tagger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_tags', related_query_name='text_tag', to='mohaverekhan.Tagger'),
        ),
        migrations.AddField(
            model_name='token',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tokens', related_query_name='token', through='mohaverekhan.TokenTag', to='mohaverekhan.Tag'),
        ),
    ]
